# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.8'

# Define services
services:
  # Frontend Service
  app-client:
    container_name: guitar-shop-client
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

  # App backend service
  app-server:
    depends_on:
      - app-db # This service depends on mysql. Start that first.
    container_name: guitar-shop-server
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    restart: on-failure
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3307/guitar_shop_db?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING.DATASOURCE.USER: root
      SPRING.DATASOURCE.PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Database Service (Mysql)
  app-db:
    container_name: guitar-shop-db
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    restart: always
    networks:
      - backend


# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: